# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from federated_inference._generated import worker_pb2 as worker__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in worker_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class WorkerServiceStub(object):
    """── Service ───────────────────────────────────────────────────────────────────

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Register = channel.unary_unary(
                '/federated_inference.WorkerService/Register',
                request_serializer=worker__pb2.RegisterRequest.SerializeToString,
                response_deserializer=worker__pb2.RegisterResponse.FromString,
                _registered_method=True)
        self.HealthCheck = channel.unary_unary(
                '/federated_inference.WorkerService/HealthCheck',
                request_serializer=worker__pb2.HealthRequest.SerializeToString,
                response_deserializer=worker__pb2.HealthResponse.FromString,
                _registered_method=True)
        self.StartRPC = channel.unary_unary(
                '/federated_inference.WorkerService/StartRPC',
                request_serializer=worker__pb2.StartRPCRequest.SerializeToString,
                response_deserializer=worker__pb2.StartRPCResponse.FromString,
                _registered_method=True)
        self.StopRPC = channel.unary_unary(
                '/federated_inference.WorkerService/StopRPC',
                request_serializer=worker__pb2.StopRPCRequest.SerializeToString,
                response_deserializer=worker__pb2.StopRPCResponse.FromString,
                _registered_method=True)
        self.StreamMetrics = channel.unary_stream(
                '/federated_inference.WorkerService/StreamMetrics',
                request_serializer=worker__pb2.MetricsRequest.SerializeToString,
                response_deserializer=worker__pb2.MetricsSnapshot.FromString,
                _registered_method=True)


class WorkerServiceServicer(object):
    """── Service ───────────────────────────────────────────────────────────────────

    """

    def Register(self, request, context):
        """One-shot RPC: coordinator calls this on startup or reconnect
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def HealthCheck(self, request, context):
        """Coordinator polls this on a schedule (e.g. every 10s)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StartRPC(self, request, context):
        """Coordinator explicitly asks the worker to start its llama-rpc-server
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StopRPC(self, request, context):
        """Coordinator asks the worker to stop its llama-rpc-server
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StreamMetrics(self, request, context):
        """Real-time streaming of device stats (optional, for dashboards)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_WorkerServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Register': grpc.unary_unary_rpc_method_handler(
                    servicer.Register,
                    request_deserializer=worker__pb2.RegisterRequest.FromString,
                    response_serializer=worker__pb2.RegisterResponse.SerializeToString,
            ),
            'HealthCheck': grpc.unary_unary_rpc_method_handler(
                    servicer.HealthCheck,
                    request_deserializer=worker__pb2.HealthRequest.FromString,
                    response_serializer=worker__pb2.HealthResponse.SerializeToString,
            ),
            'StartRPC': grpc.unary_unary_rpc_method_handler(
                    servicer.StartRPC,
                    request_deserializer=worker__pb2.StartRPCRequest.FromString,
                    response_serializer=worker__pb2.StartRPCResponse.SerializeToString,
            ),
            'StopRPC': grpc.unary_unary_rpc_method_handler(
                    servicer.StopRPC,
                    request_deserializer=worker__pb2.StopRPCRequest.FromString,
                    response_serializer=worker__pb2.StopRPCResponse.SerializeToString,
            ),
            'StreamMetrics': grpc.unary_stream_rpc_method_handler(
                    servicer.StreamMetrics,
                    request_deserializer=worker__pb2.MetricsRequest.FromString,
                    response_serializer=worker__pb2.MetricsSnapshot.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'federated_inference.WorkerService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('federated_inference.WorkerService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class WorkerService(object):
    """── Service ───────────────────────────────────────────────────────────────────

    """

    @staticmethod
    def Register(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/federated_inference.WorkerService/Register',
            worker__pb2.RegisterRequest.SerializeToString,
            worker__pb2.RegisterResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def HealthCheck(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/federated_inference.WorkerService/HealthCheck',
            worker__pb2.HealthRequest.SerializeToString,
            worker__pb2.HealthResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StartRPC(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/federated_inference.WorkerService/StartRPC',
            worker__pb2.StartRPCRequest.SerializeToString,
            worker__pb2.StartRPCResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StopRPC(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/federated_inference.WorkerService/StopRPC',
            worker__pb2.StopRPCRequest.SerializeToString,
            worker__pb2.StopRPCResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StreamMetrics(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/federated_inference.WorkerService/StreamMetrics',
            worker__pb2.MetricsRequest.SerializeToString,
            worker__pb2.MetricsSnapshot.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
